name: Weekly Crawl
on:
  schedule:
    - cron: '0 22 * * 6'  # UTC 토요일 22시 = KST 일요일 07시
  workflow_dispatch:  # 수동 실행 옵션 추가

permissions:
  contents: write  # 권한 부여 (Push 권한 활성화)

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Crawler
        run: python crawler.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Sin-Yejun"
          git config --global user.email "21900402@handong.ac.kr"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Sin-Yejun/church_paper.git
          git add img_url.txt
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update img_url.txt from weekly crawl"
            git push
          fi
